name: Deploy weat-analyze-api

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/weat-analyze-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/weat-analyze-api:latest

      - name: Deploy to Ncloud Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/weat-analyze-api:latest
            docker stop weat-analyze-api || true
            docker rm weat-analyze-api || true
            docker run -d --name weat-analyze-api -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/weat-analyze-api:latest
